services:
  postgres:
    image: postgres:latest
    container_name: n8n
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    ports:
      - "5432:5432"
    volumes:
      - n8n_pgdata:/var/lib/postgresql/data

volumes:
  n8n_pgdata:
